-- Q1: Total sales revenue by product category for each month
SELECT DP.CATEGORY, DD.DATE_MONTH, DD.DATE_YEAR, SUM(UNITS_SOLD * UNIT_PRICE) AS TOTAL_SALES
FROM FACT_SALES FS 
JOIN DIM_DATE DD USING (DATE_DMY)
JOIN DIM_PRODUCT DP USING (PRODUCT_ID)
GROUP BY CATEGORY, DD.DATE_MONTH, DD.DATE_YEAR
ORDER BY CATEGORY ASC;


-- Q2: Top 2 performing stores by total revenue
SELECT DS.STORE_NAME, SUM(UNITS_SOLD * UNIT_PRICE) AS TOTAL_REVENUE 
FROM FACT_SALES FC
JOIN DIM_STORE DS USING (STORE_ID)
GROUP BY DS.STORE_NAME
ORDER BY SUM(UNITS_SOLD * UNIT_PRICE) DESC
LIMIT 2;


-- Q3: Month-over-month sales trend across all stores
SELECT DD.DATE_MONTH, DD.DATE_YEAR, SUM(UNITS_SOLD * UNIT_PRICE) AS TOTAL_SALES 
FROM FACT_SALES FS
JOIN DIM_DATE DD USING (DATE_DMY)
GROUP BY DD.DATE_MONTH, DD.DATE_YEAR;