DROP DATABASE IF EXISTS STAR;
CREATE DATABASE STAR;
USE STAR;

CREATE TABLE DIM_PRODUCT(
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL UNIQUE,
    CATEGORY VARCHAR(100) NOT NULL
);

CREATE TABLE DIM_STORE(
    STORE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STORE_NAME VARCHAR(100) NOT NULL UNIQUE,
    STORE_CITY VARCHAR(255) NOT NULL
);

CREATE TABLE DIM_DATE(
    DATE_DMY DATE NOT NULL PRIMARY KEY,
    DATE_MONTH INT,
    DATE_YEAR INT
);

CREATE TABLE FACT_SALES(
    TRANSACTION_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    DATE_DMY DATE NOT NULL,
    STORE_ID INT NOT NULL,  
    PRODUCT_ID INT NOT NULL, 
    UNITS_SOLD INT NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (STORE_ID) REFERENCES DIM_STORE(STORE_ID),
    FOREIGN KEY (DATE_DMY) REFERENCES DIM_DATE(DATE_DMY)
);


INSERT INTO DIM_PRODUCT (PRODUCT_NAME, CATEGORY) VALUES
('Speaker', 'electronics'), ('Saree', 'clothing'), ('Tablet', 'electronics'),
('Smartwatch', 'electronics'), ('Biscuits', 'grocery'), ('Atta 10kg', 'grocery'),
('Jeans', 'clothing'), ('Headphones', 'electronics'), ('Pulses 1kg', 'grocery'),
('T-Shirt', 'clothing'), ('Jacket', 'clothing'), ('Milk 1L', 'grocery'),
('Rice 5kg', 'grocery'), ('Phone', 'electronics'), ('Laptop', 'electronics'),
('Oil 1L', 'grocery');

INSERT INTO DIM_STORE (STORE_NAME, STORE_CITY) VALUES
('Bangalore MG', 'Bangalore'), ('Delhi South', 'Delhi'), ('Chennai Anna', 'Chennai'),
('Pune FC Road', 'Pune'), ('Mumbai Central', 'Mumbai');

INSERT INTO DIM_DATE (DATE_DMY, DATE_MONTH, DATE_YEAR) VALUES
('2023-08-29', 8, 2023), ('2023-12-12', 12, 2023), ('2023-05-02', 5, 2023),
('2023-02-20', 2, 2023), ('2023-01-15', 1, 2023), ('2023-09-08', 9, 2023),
('2023-03-31', 3, 2023), ('2023-10-26', 10, 2023), ('2023-04-06', 4, 2023), 
('2023-01-18', 1, 2023), ('2023-01-08', 1, 2023), ('2023-07-22', 7, 2023), 
('2023-01-13', 1, 2023), ('2023-11-22', 11, 2023), ('2023-01-24', 1, 2023), 
('2023-03-10', 3, 2023), ('2023-03-21', 3, 2023), ('2023-08-12', 8, 2023), 
('2023-04-03', 4, 2023), ('2023-10-20', 10, 2023), ('2023-05-21', 5, 2023), 
('2023-04-28', 4, 2023), ('2023-05-12', 5, 2023), ('2023-10-27', 10, 2023), 
('2023-01-17', 1, 2023), ('2023-11-01', 11, 2023), ('2023-11-18', 11, 2023), 
('2023-08-02', 8, 2023);


INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5000', '2023-08-29', s.STORE_ID, p.PRODUCT_ID, 3, 49262.78, 'CUST045' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Speaker';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5001', '2023-12-12', s.STORE_ID, p.PRODUCT_ID, 11, 35451.81, 'CUST012' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Delhi South' AND p.PRODUCT_NAME = 'Saree';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5002', '2023-05-02', s.STORE_ID, p.PRODUCT_ID, 20, 48703.39, 'CUST019' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Tablet';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5003', '2023-02-20', s.STORE_ID, p.PRODUCT_ID, 14, 23226.12, 'CUST007' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Delhi South' AND p.PRODUCT_NAME = 'Saree';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5004', '2023-01-15', s.STORE_ID, p.PRODUCT_ID, 10, 58851.01, 'CUST004' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Smartwatch';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5005', '2023-09-08', s.STORE_ID, p.PRODUCT_ID, 12, 52464.00, 'CUST027' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Atta 10kg';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5006', '2023-03-31', s.STORE_ID, p.PRODUCT_ID, 5, 58851.01, 'CUST025' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Pune FC Road' AND p.PRODUCT_NAME = 'Smartwatch';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5007', '2023-10-26', s.STORE_ID, p.PRODUCT_ID, 16, 2317.47, 'CUST041' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Pune FC Road' AND p.PRODUCT_NAME = 'Jeans';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5008', '2023-08-12', s.STORE_ID, p.PRODUCT_ID, 9, 27469.99, 'CUST030' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Biscuits';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5009', '2023-04-03', s.STORE_ID, p.PRODUCT_ID, 18, 39854.96, 'CUST045' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Headphones';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5010', '2023-04-06', s.STORE_ID, p.PRODUCT_ID, 15, 30187.24, 'CUST031' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Biscuits';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5011', '2023-10-20', s.STORE_ID, p.PRODUCT_ID, 13, 2317.47, 'CUST045' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Jeans';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5012', '2023-05-21', s.STORE_ID, p.PRODUCT_ID, 13, 42343.15, 'CUST044' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Laptop';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5013', '2023-04-28', s.STORE_ID, p.PRODUCT_ID, 10, 43374.39, 'CUST015' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Milk 1L';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5014', '2023-11-18', s.STORE_ID, p.PRODUCT_ID, 5, 30187.24, 'CUST042' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Delhi South' AND p.PRODUCT_NAME = 'Jacket';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5015', '2023-01-18', s.STORE_ID, p.PRODUCT_ID, 15, 35451.81, 'CUST009' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Saree';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5016', '2023-01-08', s.STORE_ID, p.PRODUCT_ID, 11, 35451.81, 'CUST035' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Saree';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5017', '2023-05-12', s.STORE_ID, p.PRODUCT_ID, 6, 30187.24, 'CUST019' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Jacket';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5018', '2023-08-02', s.STORE_ID, p.PRODUCT_ID, 15, 39854.96, 'CUST015' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Headphones';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5019', '2023-07-22', s.STORE_ID, p.PRODUCT_ID, 3, 52464.00, 'CUST008' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Atta 10kg';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5020', '2023-10-27', s.STORE_ID, p.PRODUCT_ID, 9, 52464.00, 'CUST024' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Speaker';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5021', '2023-01-13', s.STORE_ID, p.PRODUCT_ID, 16, 2317.47, 'CUST036' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Jeans';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5022', '2023-11-22', s.STORE_ID, p.PRODUCT_ID, 13, 2317.47, 'CUST020' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Bangalore MG' AND p.PRODUCT_NAME = 'Jeans';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5023', '2023-01-24', s.STORE_ID, p.PRODUCT_ID, 5, 39854.96, 'CUST032' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Headphones';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5024', '2023-03-10', s.STORE_ID, p.PRODUCT_ID, 8, 39854.96, 'CUST032' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Headphones';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5025', '2023-03-21', s.STORE_ID, p.PRODUCT_ID, 9, 31604.47, 'CUST032' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Pune FC Road' AND p.PRODUCT_NAME = 'Pulses 1kg';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5026', '2023-01-17', s.STORE_ID, p.PRODUCT_ID, 19, 31604.47, 'CUST029' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Pune FC Road' AND p.PRODUCT_NAME = 'Pulses 1kg';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5027', '2023-02-20', s.STORE_ID, p.PRODUCT_ID, 12, 2317.47, 'CUST042' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Chennai Anna' AND p.PRODUCT_NAME = 'Jeans';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5028', '2023-05-02', s.STORE_ID, p.PRODUCT_ID, 18, 49262.78, 'CUST036' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Mumbai Central' AND p.PRODUCT_NAME = 'Speaker';
INSERT INTO FACT_SALES (TRANSACTION_ID, DATE_DMY, STORE_ID, PRODUCT_ID, UNITS_SOLD, UNIT_PRICE, CUSTOMER_ID)
SELECT 'TXN5029', '2023-11-01', s.STORE_ID, p.PRODUCT_ID, 20, 29770.19, 'CUST016' FROM DIM_STORE s, DIM_PRODUCT p WHERE s.STORE_NAME = 'Delhi South' AND p.PRODUCT_NAME = 'T-Shirt';