-- Q1: List all customers from Mumbai along with their total order value
SELECT C.CUSTOMER_NAME, SUM(OD.QUANTITY * P.UNIT_PRICE) AS TOTAL_ORDER_VALUE, CUSTOMER_CITY FROM CUSTOMERS C
JOIN ORDERS O USING (CUSTOMER_ID)
JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
JOIN PRODUCT P ON OD.PRODUCT_ID = P.PRODUCT_ID
WHERE C.CUSTOMER_CITY = 'MUMBAI'
GROUP BY C.CUSTOMER_NAME;

-- Q2: Find the top 3 products by total quantity sold
SELECT PRODUCT_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD FROM PRODUCT
JOIN ORDER_DETAILS USING (PRODUCT_ID)
GROUP BY PRODUCT_ID
ORDER BY SUM(QUANTITY) DESC
LIMIT 3;

-- Q3: List all sales representatives and the number of unique customers they have handled
SELECT DISTINCT SALES_REP_NAME, CUSTOMER_NAME FROM SALES_REP
LEFT JOIN ORDERS O USING (SALES_REP_ID)
LEFT JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
;

-- Q4: Find all orders where the total value exceeds 10,000, sorted by value descending
SELECT OD.ORDER_ID, SUM(OD.QUANTITY * P.UNIT_PRICE) AS TOTAL_VALUE FROM ORDER_DETAILS OD
JOIN PRODUCT P USING (PRODUCT_ID)
GROUP BY OD.ORDER_ID
HAVING SUM(OD.QUANTITY * P.UNIT_PRICE) > 10000
ORDER BY SUM(OD.QUANTITY * P.UNIT_PRICE) DESC;

-- Q5: Identify any products that have never been ordered
SELECT DISTINCT P.PRODUCT_ID, P.PRODUCT_NAME, OD.PRODUCT_ID FROM PRODUCT P
LEFT JOIN ORDER_DETAILS OD USING (PRODUCT_ID)
WHERE OD.PRODUCT_ID IS NULL;